CREATE DATABASE ARQUITECTURA;



CREATE TABLE PROFESOR (
    ID INT NOT NULL AUTO_INCREMENT,
    NOMBRE VARCHAR(100) NOT NULL,
    APELLIDO VARCHAR(100) NOT NULL,
    CI VARCHAR(30) NOT NULL,
    SEXO VARCHAR(1),
    DIRECCION VARCHAR(100),
    TELEFONO INTEGER(30),
    CORREO VARCHAR(100) NOT NULL,
    PASSWORD VARCHAR(100)NOT NULL,
    PRIMARY KEY (ID)
); 
INSERT INTO PROFESOR ( NOMBRE, APELLIDO, CI, SEXO, DIRECCION, TELEFONO, CORREO, PASSWORD) VALUES
        ("MARIA", "PEREZ" , "ARNEZ" , "99602583" , "B.AURELIO/C.TOBOROCHI/NRO.34" , 76690968 , "maria@gmail.com" , "e10adc3949ba59abbe56e057f20f883e"),
        ("ELDA", "RIVERA", "ACOSTA" , "93423122" , "B.CENTRAL/C.TOBOROCHI/NRO.35" , 69287451, "elda@gmail.com" , "e10adc3949ba59abbe56e057f20f883e"),
        ("ANTONIO", "PEREDO", "SUAREZ" , "71017578" , "B.CENTRAL/C.TOBOROCHI/NRO.36" , 58453257 , "antonio@gmail.com", "e10adc3949ba59abbe56e057f20f883e");
		
CREATE TABLE CURSO(
    ID INT NOT NULL AUTO_INCREMENT,
    NOMBRE VARCHAR(50) NOT NULL,
    PARALELO CHAR(1) NOT NULL,
	DESCRIPCION VARCHAR(100),
    PRIMARY KEY (ID)
); 

INSERT INTO CURSO ( NOMBRE, PARALELO,DESCRIPCION ) VALUES
        ("1 ", "A" , "SECUNDARIA"),
		("1 ", "B" , "SECUNDARIA"),
		("2", "A" , "SECUNDARIA");
	
CREATE TABLE TIPOACTIVIDAD(
    ID INT NOT NULL AUTO_INCREMENT,
    NOMBRE VARCHAR(255) NOT NULL,
	DESCRIPCION VARCHAR(255) NOT NULL,
    PRIMARY KEY (ID)
); 
INSERT INTO TIPOACTIVIDAD ( NOMBRE, DESCRIPCION ) VALUES
        ("PRACTICOS ", "NOTA DE PONDERACION 30 PUNTOS" ),
		("EXAMENES ", "NOTA DE PONDERACION 40 PUNTOS" ),
		("INVESTIGACIONES", "NOTA DE PONDERACION 30 PUNTOS" );

CREATE TABLE MATERIA(
    ID INT NOT NULL AUTO_INCREMENT,
    NOMBRE VARCHAR(100) NOT NULL,
    PRIMARY KEY (ID)
);
INSERT INTO MATERIA ( NOMBRE) VALUES
        ("MATEMATICAS "),
		("LENGUAJE "),
		("FISICA "),
		("QUIMICA "),
		("ARTES PLASTICAS "),
		("CIENCIAS NATURALES "),
		("CIENCIAS SOCIALES "),
		("BIOLOGIA "),
		("INGLES");

CREATE TABLE GESTION(
    ID INT NOT NULL AUTO_INCREMENT,
	NOMBRE VARCHAR(10) NOT NULL,
    FECHA_INICIO VARCHAR(100) NOT NULL,
    FECHA_FIN VARCHAR(100) NOT NULL,
    PROFESOR_ID INT NOT NULL,
	PRIMARY KEY (ID),
	FOREIGN KEY (PROFESOR_ID) REFERENCES PROFESOR(ID)
);

INSERT INTO GESTION ( NOMBRE,FECHA_INICIO, FECHA_FIN , PROFESOR_ID) VALUES
        ("1" ,"01/02/2021" , "30/04/2021" ,2 ),
		("2" ,"01/05/2021" , "31/07/2021" ,2),
		("3" ,"01/08/2021" , "30/11/2021" ,2);

CREATE TABLE GESTIONMATERIA(
    ID INT NOT NULL AUTO_INCREMENT,
	GESTION_ID INT NOT NULL,
	MATERIA_ID INT NOT NULL,
	CURSO_ID INT NOT NULL,
    PRIMARY KEY (ID),
    FOREIGN KEY (GESTION_ID) REFERENCES GESTION(ID),
	FOREIGN KEY (MATERIA_ID) REFERENCES MATERIA(ID),
    FOREIGN KEY (CURSO_ID) REFERENCES CURSO(ID)
);
INSERT INTO GESTIONMATERIA ( GESTION_ID,MATERIA_ID, CURSO_ID ) VALUES
        (1, 1 ,1),
		(1, 3 ,1),
		(1, 5 ,1),
	    (1, 1 ,2),
		(1, 3 ,2),
		(1, 5 ,2);

CREATE TABLE ACTIVIDAD(
    ID INT NOT NULL AUTO_INCREMENT,
    NOMBRE VARCHAR(255) NOT NULL,
    FECHA VARCHAR(100) NOT NULL,
    DOCUMENTO VARCHAR(255) NOT NULL,
	GESTIONMATERIA_ID INT NOT NULL,
	TIPOACTIVIDAD_ID INT NOT NULL,
    PRIMARY KEY (ID),
	FOREIGN KEY (GESTIONMATERIA_ID) REFERENCES GESTIONMATERIA(ID),
	FOREIGN KEY (TIPOACTIVIDAD_ID) REFERENCES TIPOACTIVIDAD(ID)
); 
INSERT INTO ACTIVIDAD ( NOMBRE,FECHA, DOCUMENTO , GESTIONMATERIA_ID , TIPOACTIVIDAD_ID ) VALUES
        ("15 EJERCIOS CASOS DE FACTORIZACION" ,"26/02/2021" ,"15 EJERCICIOS.PDF" ,"1" ,"1" ),
        ("15 EJERCIOS CASOS DE FACTORIZACION" ,"06/03/2021" ,"15 EJERCICIOS.PDF" ,"1" ,"1" ),
        ("15 EJERCIOS CASOS DE FACTORIZACION" ,"13/04/2021" ,"15 EJERCICIOS.PDF" ,"1" ,"1" ),
		
        ("4 EJERCICIO EXAMEN 1" ,"28/04/2021" ,"PRIMER_EXAMEN.PDF" ,"1" ,"2" ),
		
        ("PRIMERA INVESTIGACION" ,"01/02/2021" ,"PUNTOS_DE_INVESTIGACION_1.PDF" ,"1" ,"3" );



